### ISSUE TITLE
[BUG 🐜]Game loading failed

### ISSUE THREAD

**Issue by Rhaaaaaast1** [Lucreeper74/Create-Metallurgy#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<html>
<body>

java.lang.Exception: Mod Loading has failed
8 | at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.1-universal.jar%23443!/:?] {re:classloading}
9 | at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.1-universal.jar%23443!/:?] {re:classloading,pl:runtimedistcleaner:A}
10 | at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
11 | at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:A}
12 | at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
13 | at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.1-universal.jar%23443!/:?] {re:classloading,re:mixin,pl:mixin:A}
14 | at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:client.MixinGameRenderer,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:brewery-common.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.cofhcore.json:GameRendererMixin,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:corgilib.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:tweakerge.mixins.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
15 | at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
16 | at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
17 | at net.minecraft.client.main.Main.main(Main.java:218) ~[CreateTechNewHorizon.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
18 | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
19 | at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
20 | at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
21 | at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
22 | at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
23 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
24 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
25 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
26 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
27 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
28 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
29 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
30 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
31 | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
32 | at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
33 | at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?] {}
34 | at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?] {}
35 |  
36 |  
37 | A detailed walkthrough of the error, its code path and all known details is as follows:
38 | ---------------------------------------------------------------------------------------
39 |  
40 | -- Head --
41 | Thread: Render thread
42 | Suspected Mod:
43 | Flywheel (flywheel), Version: 0.6.10-7
44 | Issue tracker URL: https://github.com/Jozufozu/Flywheel/issues
45 | at TRANSFORMER/flywheel@0.6.10-7/com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31)
46 | Stacktrace:
47 | at com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31) ~[flywheel-forge-1.20.1-0.6.10-7.jar%23509!/:0.6.10-7] {re:mixin,re:classloading,pl:mixin:A}
48 | -- MOD createmetallurgy --
49 | Details:
50 | Caused by 0: java.lang.ExceptionInInitializerError
51 | at fr.lucreeper74.createmetallurgy.CreateMetallurgyClient.clientInit(CreateMetallurgyClient.java:14) ~[createmetallurgy-0.0.3-1.20.1.jar%23388!/:0.0.3-1.20.1] {re:classloading}
52 | at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?] {}
53 | at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?] {}
54 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
55 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
56 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.3.1.jar%23440!/:?] {}
57 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.3.1.jar%23439!/:?] {re:mixin}
58 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
59 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
60 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
61 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
62 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
63 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
64 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
65 |  
66 | Mod File: /E:/PCL2/.minecraft/versions/CreateTechNewHorizon/mods/createmetallurgy-0.0.3-1.20.1.jar
67 | Failure message: Create Metallurgy (createmetallurgy) encountered an error during the sided_setup event phase
68 | java.lang.ExceptionInInitializerError: null
69 | Mod Version: 0.0.3-1.20.1
70 | Mod Issue URL: NOT PROVIDED
71 | Exception message: java.lang.RuntimeException: PartialModel 'createmetallurgy:block/foundry_mixer/pole' loaded after ModelEvent.RegisterAdditional
72 | Stacktrace:
73 | at com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31) ~[flywheel-forge-1.20.1-0.6.10-7.jar%23509!/:0.6.10-7] {re:mixin,re:classloading,pl:mixin:A}
74 | at fr.lucreeper74.createmetallurgy.registries.CMPartialModels.block(CMPartialModels.java:35) ~[createmetallurgy-0.0.3-1.20.1.jar%23388!/:0.0.3-1.20.1] {re:classloading}
75 | at fr.lucreeper74.createmetallurgy.registries.CMPartialModels.<clinit>(CMPartialModels.java:15) ~[createmetallurgy-0.0.3-1.20.1.jar%23388!/:0.0.3-1.20.1] {re:classloading}
76 | at fr.lucreeper74.createmetallurgy.CreateMetallurgyClient.clientInit(CreateMetallurgyClient.java:14) ~[createmetallurgy-0.0.3-1.20.1.jar%23388!/:0.0.3-1.20.1] {re:classloading}
77 | at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?] {}
78 | at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?] {}
79 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
80 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
81 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.3.1.jar%23440!/:?] {}
82 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.3.1.jar%23439!/:?] {re:mixin}
83 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
84 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
85 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
86 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
87 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
88 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
89 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
90

<br class="Apple-interchange-newline">
</body>
</html>
**Environment:**
 - MC/Forge version
 - Create version
 - Create Metallurgy version
- Others mods / modpacks, datapacks

**Additional context**
Add any other context or revelant details about the problem here.
java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.1-universal.jar%23443!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:13[8](https://mclo.gs/FrOaAYk#L8)) ~[forge-1.20.1-47.3.1-universal.jar%23443!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.1-universal.jar%23443!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_10[9](https://mclo.gs/FrOaAYk#L9)093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:client.MixinGameRenderer,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:brewery-common.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.cofhcore.json:GameRendererMixin,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:corgilib.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:tweakerge.mixins.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[CreateTechNewHorizon.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:[10](https://mclo.gs/FrOaAYk#L10)3) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Flywheel (flywheel), Version: 0.6.10-7
		Issue tracker URL: https://github.com/Jozufozu/Flywheel/issues
		at TRANSFORMER/flywheel@0.6.10-7/com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31)
Stacktrace:
	at com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31) ~[flywheel-forge-1.20.1-0.6.10-7.jar%23509!/:0.6.10-7] {re:mixin,re:classloading,pl:mixin:A}
-- MOD createmetallurgy --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at fr.lucreeper74.createmetallurgy.CreateMetallurgyClient.clientInit(CreateMetallurgyClient.java:14) ~[createmetallurgy-0.0.3-1.20.1.jar%23388!/:0.0.3-1.20.1] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$[11](https://mclo.gs/FrOaAYk#L11)(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.3.1.jar%23440!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:[12](https://mclo.gs/FrOaAYk#L12)5) ~[fmlcore-1.20.1-47.3.1.jar%23439!/:?] {re:mixin}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:[13](https://mclo.gs/FrOaAYk#L13)12) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}

	Mod File: /E:/PCL2/.minecraft/versions/CreateTechNewHorizon/mods/createmetallurgy-0.0.3-1.20.1.jar
	Failure message: Create Metallurgy (createmetallurgy) encountered an error during the sided_setup event phase
		java.lang.ExceptionInInitializerError: null
	Mod Version: 0.0.3-1.20.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: PartialModel 'createmetallurgy:block/foundry_mixer/pole' loaded after ModelEvent.RegisterAdditional
Stacktrace:
	at com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31) ~[flywheel-forge-1.20.1-0.6.10-7.jar%23509!/:0.6.10-7] {re:mixin,re:classloading,pl:mixin:A}
	at fr.lucreeper74.createmetallurgy.registries.CMPartialModels.block(CMPartialModels.java:35) ~[createmetallurgy-0.0.3-1.20.1.jar%23388!/:0.0.3-1.20.1] {re:classloading}
	at fr.lucreeper74.createmetallurgy.registries.CMPartialModels.<clinit>(CMPartialModels.java:15) ~[createmetallurgy-0.0.3-1.20.1.jar%23388!/:0.0.3-1.20.1] {re:classloading}
	at fr.lucreeper74.createmetallurgy.CreateMetallurgyClient.clientInit(CreateMetallurgyClient.java:[14](https://mclo.gs/FrOaAYk#L14)) ~[createmetallurgy-0.0.3-1.20.1.jar%23388!/:0.0.3-1.20.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.3.1.jar%23440!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.3.1.jar%23439!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}

**Comment by Lucreeper74** [comment]
Hey @Rhaaaaaast1!
This is a know issue on 1.19.2 for players who use v.3.5 of Modpack All Of Create but seems to be also on 1.20. This is weird cause its not for everyone who play with that version, seems to be random and due to others mods from your modpack, cause I can't be able to reproduce the bug.
Being currently off for Create Metallurgy developement for a few days for personnal reason (Dates are writed on Create Metallurgy Discord server), I will actively search for this after that.
Thanks for your understanding and taking the time to report bugs, that help me to improve Create Metallurgy!

**Comment by Rhaaaaaast1** [comment]
thank u very much.

**Comment by Lucreeper74** [comment]
I forgot to give news here, I said on discord, I have found the bug and maybe a fix, waiting the end of my break to test it.

**Comment by Lucreeper74** [comment]
Hey :wave: 
I finally pushed the fix to github in this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/bcc8107ca17c813b83ce49de4a233965a154dc13), and will port it tomorrow. I was busy with other issues and optimizations with my mod which took some time. But it is done. I hope this will fix the issue. This will be available in the next update! I will re-open this thread to give information in case of this will won't fix the issue.
